[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino
monitor_speed = 115200
board_build.flash_mode = qio
board_build.f_flash = 80000000L
lib_deps =
    espressif/esp32-camera
upload_port = COM6
upload_speed = 921600
